name: Build and Test

env:
  DOTNET_VERSION: '8.0.x'

on:
  pull_request: 
    branches:
      - main
    paths:
      - '**.cs'
      - '**.csproj'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - name: 'Restore dependencies'
        run: dotnet restore
      - name: 'Build'
        run: dotnet build --configuration Release --no-restore
      - name: 'Test'
        run: dotnet test --no-restore --verbosity normal
