name: Deploy Images to GHCR

env:
  DOTNET_VERSION: '8.0.x'

on:
  push:
    branches:
      - main
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - name: 'Restore dependencies'
        run: dotnet restore
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Create and Publish Docker Image'
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            dotnet publish ./FL.LigaImmich/FL.LigaImmich.csproj /t:PublishContainer -r linux-x64 \
              -p:ContainerImageTag=${{ github.event.release.tag_name }}
          else
            dotnet publish ./FL.LigaImmich/FL.LigaImmich.csproj /t:PublishContainer -r linux-x64
          fi
