name: Deploy Images to GHCR

env:
  DOTNET_VERSION: '8.0.x'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './FL.LigaImmich'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build and push'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mstroppel/LigaImmich:latest


