name: Deploy Images to GHCR

env:
  DOTNET_VERSION: '8.0.x'

on:
  push:
    branches:
      - main
      - feat/try-one
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Test
        run: dotnet test --no-build --verbosity normal -c Release
      - name: Create Docker Image
        run: dotnet publish ./FL.LigaImmich/FL.LigaImmich.csproj /t:PublishContainer -r linux-x64
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Docker Push
        run: docker push liga-immich
